# 数据源配置
spring:
#Redis配置
    redis:
#Redis数据库索引（默认为0）
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 20
            max-wait: 200
            max-idle: 10
            min-idle: 0
        timeout: 1000
server:
    servlet:
        context-path: /suncent-sso-b
    port: 8082
    uri-encoding: utf-8
#日志  如果日志配置文件为“log4j2-spring.xml”，就可以不用此配置了
#logging:
#    config: xxxx.xml
#    level:
#        cn.jay.repository: trace