#自定义参数
amtupath: D:/AMTUData/production/outgoing/
# 数据源配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/suncent_fitment?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: suncent_MySql996
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 5  
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000  
            min-evictable-idle-time-millis: 300000  
            validation-query: SELECT 1 FROM DUAL  
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20  
            filters:
                commons-log:
                    connection-logger-name: stat,wall,log4j 
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: /*/.js,/*/.gif,/*/.jpg,/*/.png,/*/.css,/*/.ico,/druid/*
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: druid
                login-password: druid123
    jpa:
        show-sql: false
        
#Redis配置
    redis:
#Redis数据库索引（默认为0）
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
        max-active: 20
        max-wait: 200
        max-idle: 10
        min-idle: 0
        timeout: 1000
        
    activemq:
        broker-url: tcp://127.0.0.1:61616
        user: admin
        password: suncent_IT996
        close-timeout: 15s   # 在考虑结束之前等待的时间
        in-memory: true      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
        non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留
        send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
        queue-name: active.queue
        topic-name: active.topic.name.model

server:
    servlet:
        context-path: /iFitment-convert
    port: 8084
    uri-encoding: utf-8
# mybatis 配置
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
logging:
    level:
        com:
            suncent:
                fitment:
                    convert:
                        mapper: debug