spring:
#Redis
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 20
            max-wait: 200
            max-idle: 10
            min-idle: 0
        timeout: 1000
#ftl配置
#设定ftl文件路径
    springfreemarker:
        template-loader-path: classpath:/templates
    freemarker:
        request-context-attribute: request
#httpclient
http:
    maxTotal: 100
    defaultMaxPerRoute: 20
    connectTimeout: 1000
    connectionRequestTimeout: 500
    socketTimeout: 10000
    staleConnectionCheckEnabled: true
server:
    servlet:
        context-path: /suncent-sso-a
    port: 8081
    uri-encoding: utf-8
#日志  如果日志配置文件为“log4j2-spring.xml”，就可以不用此配置了
#logging:
#    config: xxxx.xml
#    level:
#        cn.jay.repository: trace