# 数据源配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/suncent_ms?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&useLegacyDatetimeCode=false&useJDBCCompliantTimezoneShift=true&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: suncent_mysql321
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 5  
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000  
            min-evictable-idle-time-millis: 300000  
            validation-query: SELECT 1 FROM DUAL  
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20  
            filters:
                commons-log:
                    connection-logger-name: stat,wall,log4j 
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: /*/.js,/*/.gif,/*/.jpg,/*/.png,/*/.css,/*/.ico,/druid/*
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: druid
                login-password: druid123
#ftl配置
#设定ftl文件路径
    springfreemarker:
        template-loader-path: classpath:/templates
    freemarker:
        request-context-attribute: request
#Redis配置
    redis:
#Redis数据库索引（默认为0）
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 20
            max-wait: 200
            max-idle: 10
            min-idle: 0
        timeout: 1000
server:
    servlet:
        context-path: /suncent-sso
    port: 8080
    uri-encoding: utf-8
# mybatis 配置
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
#日志  如果日志配置文件为“log4j2-spring.xml”，就可以不用此配置了
#logging:
#    config: xxxx.xml
#    level:
#        cn.jay.repository: trace